### PR TITLE
Fix Falcon3 compatibility issue on GET endpoints

### PR DESCRIPTION
**Pull request by mortymacs**
Issue https://github.com/0b01001001/spectree/pull/137

### CODE REVIEW

**Comment by kemingy** [comment]
I think GitHub is having some issues now. Let's wait for the GitHub CI. 🤣

**Comment by mortymacs** [comment]
Now it's ready :+1:

**Comment by mortymacs** [comment]
Thanks!
When you'll release a tag?

**Comment by kemingy** [comment]
Wait, I found that this PR introduces another issue. In Falcon 2, there is no MediaNotFoundError.

```ImportError: cannot import name 'MediaNotFoundError' from 'falcon'```

Can you help fix this one? I think there are lots of people using falcon 2.

**Comment by mortymacs** [comment]
Oh! I'm gonna fix it now

**Pull request merged**
