### PR TITLE
Catch route parameter keywords from schema when parsing params

### PR DESCRIPTION
**Pull request by jonathanlintott**
To solve issue #107

### CODE REVIEW

**Comment by jonathanlintott** [comment]
I'm not sure why the `lint` and `test` checks are not running.

**Comment by kemingy** [comment]
That's weird. According to the GitHub Actions setting: https://github.com/0b01001001/spectree/blob/d7cd12d7edc4baffc69f89912806d2db6d09bc23/.github/workflows/pythonpackage.yml#L4-L8, all the pull requests will trigger the lint and test.

Never mind. I can run it locally.

**Comment by kemingy** [comment]
Hi @jonathanlintott can you run the following cmd:
```sh
make lint
make test
```
To format the code, can run `make format`.

**Comment by jonathanlintott** [comment]
> To format the code, can run `make format`.

Have run `make format` as requested. However it's changed a lot more code than this PR originally did.

**Comment by kemingy** [comment]
> Have run `make format` as requested. However it's changed a lot more code than this PR originally did.

I think it's because you are using a different version of `black`.

You can create a virtualenv and run:
```sh
make install
make format
make lint
make test
```

**Comment by jonathanlintott** [comment]
> > Have run `make format` as requested. However it's changed a lot more code than this PR originally did.
> 
> I think it's because you are using a different version of `black`.
> 
> You can create a virtualenv and run:
> 
> ```shell
> make install
> make format
> make lint
> make test
> ```

I'm working from a company machine so I'm limited to what packages I can access and what versions we have of them available that's passed our internal audit. 

Regarding the failing falcon test, I get the same failing result on the master branch as well as this branch. I would have assumed it was a package mismatch except that it's happening on this CI as well.

**Comment by kemingy** [comment]
> Regarding the failing falcon test, I get the same failing result on the master branch as well as this branch. I would have assumed it was a package mismatch except that it's happening on this CI as well. Maybe there's some new falcon package that's not compatible with spectree master?

Yeah. That's because falcon just released 3.0. I think I need to fix the test.

**Comment by kemingy** [comment]
#116 should be able to fix the falcon 3 issues. You can try to pull the latest changes.

**Comment by jonathanlintott** [comment]
> #116 should be able to fix the falcon 3 issues. You can try to pull the latest changes.

Aye that works now. I'll wait until you merge #116 then I'll rebase this branch.

**Comment by kemingy** [comment]
> Aye that all passes now. I'll wait until you merge #116 then I'll rebase this branch.

Merged

**Comment by jonathanlintott** [comment]
Would it be possible to release a v0.4.2 or v0.5.0 after this PR?

**Review by kemingy — COMMENTED** [review]
LGTM. Will release a new version.

**Pull request merged**
