### PR TITLE
Add flask Blueprint support

### PR DESCRIPTION
**Pull request by hkwi**
Transparently use blueprint in place of flask app.

### CODE REVIEW

**Comment by kemingy** [comment]
Thanks for your contribution.

The current version also supports Flask blueprint. Can you brief the difference?

**Comment by hkwi** [comment]
I think, with current version, there would be 3 steps.

- We have SpecTree instance in the flask Blueprint based app to decorate the view functions.
- register that blueprint based app to the parent flask app by `app.register_blueprint`
- call spectree register_app with *parent* flask app as argument.

This patch enables register_app argument to be Blueprint.

**Comment by kemingy** [comment]
Are you trying to solve the "cycling import" problem? I think this can be avoided by registering the spectree to the flask app later. So you can have a global spectree instance and use it for all the blueprints. Then register the spectree instance to the flask app.

**Comment by hkwi** [comment]
I use blueprint to create modular application, and that application is sometime a REST application, sometime not. I wanted to encapsulate the usage of spectree in a blueprint app, and hide spectree from parent flask app `register_blueprint` code for simplicity.

**Comment by kemingy** [comment]
OK I see. Acutally you can do this with `SpecTree(mode='strict')`. So only the endpoints decorated by this instance will be displayed in the OpenAPI document. Will this be a solution for you?

**Comment by hkwi** [comment]
My understanding is that `strict` mode changes the collection of the api endpoint entries. What I wanted to hide was global spectree instance in the code, and use the blueprint app in the same way with the other non-spectree blueprint apps.

For example, blueprint app like this:

```
from flask import Blueprint, jsonify
from pydantic import BaseModel
from spectree import SpecTree, Response

simple_page = Blueprint('simple_page', __name__)
api = SpecTree('flask')

class Page(BaseModel):
	text: str

@simple_page.route("/", methods=["GET"])
@api.validate(resp=Response(HTTP_200=Page))
def show():
	return jsonify({"text":"hello"})

api.register(simple_page) # here I want to use flask Blueprint
```

and register the blueprint to Flask instance

```
from flask import Flask
from yourpackage.simple_page import simple_page

app = Flask(__name__)
app.register_blueprint(simple_page)

## WITHOUT following extra code
# from yourpackage.simple_page import api
# api.register(app)
```

The example does not work with current spectree with following error:

```
[2020-10-06 09:46:43,523] ERROR in app: Exception on /apidoc/openapi.json [GET]
Traceback (most recent call last):
  File "/home/kawai/test/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/kawai/test/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/kawai/test/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/kawai/test/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/kawai/test/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/kawai/test/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/kawai/test/lib/python3.8/site-packages/spectree/plugins/flask_plugin.py", line 149, in <lambda>
    lambda: jsonify(self.spectree.spec),
  File "/home/kawai/test/lib/python3.8/site-packages/spectree/spec.py", line 60, in spec
    self._spec = self._generate_spec()
  File "/home/kawai/test/lib/python3.8/site-packages/spectree/spec.py", line 150, in _generate_spec
    for route in self.backend.find_routes():
  File "/home/kawai/test/lib/python3.8/site-packages/spectree/plugins/flask_plugin.py", line 9, in find_routes
    for rule in self.app.url_map.iter_rules():
AttributeError: 'Blueprint' object has no attribute 'url_map'
127.0.0.1 - - [06/Oct/2020 09:46:43] "GET /apidoc/openapi.json HTTP/1.1" 500 -
```

**Comment by kemingy** [comment]
OK. So in this way, if you register the spectree instance to a blueprint, should the path be `/<blueprint-prefix>/apidoc/openapi.json`? So it doesn't affect other blueprints. Can you provide the test cases?

**Comment by hkwi** [comment]
I added the test case. Looks OK?

**Comment by kemingy** [comment]
Yeah, looks OK. Thank you.

**Pull request merged**
