### PR TITLE
Customize UI from principal project Falcon 

### PR DESCRIPTION
**Pull request by oscfrayle**
# clean url:

 /api/v1/docs

# UI Config, the UI can be in the principal project

api = SpecTree(
    'falcon',
    title=TITLE,
    version=VERSION,
    path=PATH,
    ui=PAGES["swagger"]  # redoc
)

# UI Config, without param " ui ", native library default 
api = SpecTree(
    'falcon',
    title=TITLE,
    version=VERSION,
    path=PATH
)

### CODE REVIEW

**Comment by kemingy** [comment]
Will two UI (swagger and redoc) cause any problems?

**Comment by oscfrayle** [comment]
> Will two UI (swagger and redoc) cause any problems?

none Sir, they work without problem, however, with this change it is more flexible to modify the swagger and readoc template according to the documentation, for example:
  deepLinking: true,
             presets: [
             SwaggerUIBundle.presets.apis,
             SwaggerUIStandalonePreset
             ],
             plugins: [
             SwaggerUIBundle.plugins.DownloadUrl
             ],
             layout: "BaseLayout"

in the case of swagger use:

deepLinking: false,
layout: "BaseLayout"

among other customizations

**Comment by kemingy** [comment]
OK, I see. Please make it pass the CI.

**Comment by kemingy** [comment]
Close this PR due to the following changes:
* #180

**Pull request closed without merging**
